"""create core credchain tables

Revision ID: 662bf9b6fad9
Revises: 
Create Date: 2026-08-22 09:37:54.201650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662bf9b6fad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'institution', 'verifier', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('activity_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_user_id'), 'activity_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=True)
    op.create_table('institutions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_user_id'), 'institutions', ['user_id'], unique=True)
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_identifier', sa.String(length=100), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_institution_id'), 'students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_students_student_identifier'), 'students', ['student_identifier'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('credential_requests',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', 'expired', name='credential_request_status'), nullable=False),
    sa.Column('requested_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_requests_company_id'), 'credential_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_credential_requests_status'), 'credential_requests', ['status'], unique=False)
    op.create_index(op.f('ix_credential_requests_student_id'), 'credential_requests', ['student_id'], unique=False)
    op.create_index('ix_credential_requests_student_status', 'credential_requests', ['student_id', 'status'], unique=False)
    op.create_table('credentials',
    sa.Column('credential_identifier', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.Enum('degree', 'transcript', 'migration', 'internship', 'certification', 'course', name='credential_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='credential_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_credential_identifier'), 'credentials', ['credential_identifier'], unique=True)
    op.create_index(op.f('ix_credentials_credential_type'), 'credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_credentials_institution_id'), 'credentials', ['institution_id'], unique=False)
    op.create_index(op.f('ix_credentials_status'), 'credentials', ['status'], unique=False)
    op.create_index(op.f('ix_credentials_student_id'), 'credentials', ['student_id'], unique=False)
    op.create_index('ix_credentials_student_status', 'credentials', ['student_id', 'status'], unique=False)
    op.create_table('share_grants',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Enum('view_only', name='share_permission'), nullable=False),
    sa.Column('share_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_grants_company_id'), 'share_grants', ['company_id'], unique=False)
    op.create_index(op.f('ix_share_grants_share_token_hash'), 'share_grants', ['share_token_hash'], unique=True)
    op.create_index('ix_share_grants_student_company', 'share_grants', ['student_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_share_grants_student_id'), 'share_grants', ['student_id'], unique=False)
    op.create_table('credential_documents',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_documents_content_hash'), 'credential_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_credential_documents_credential_id'), 'credential_documents', ['credential_id'], unique=True)
    op.create_table('share_grant_credentials',
    sa.Column('share_grant_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_grant_id'], ['share_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_grant_id', 'credential_id')
    )
    op.create_index(op.f('ix_share_grant_credentials_credential_id'), 'share_grant_credentials', ['credential_id'], unique=False)
    op.create_table('verification_events',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Enum('VERIFIED', 'INVALID', 'REVOKED', 'EXPIRED', 'UNAUTHORIZED', name='verification_result_status'), nullable=False),
    sa.Column('issuer_valid', sa.Boolean(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('integrity_valid', sa.Boolean(), nullable=False),
    sa.Column('status_valid', sa.Boolean(), nullable=False),
    sa.Column('access_valid', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_events_company_id'), 'verification_events', ['company_id'], unique=False)
    op.create_index('ix_verification_events_credential_company', 'verification_events', ['credential_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_verification_events_credential_id'), 'verification_events', ['credential_id'], unique=False)
    op.create_index(op.f('ix_verification_events_result'), 'verification_events', ['result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_events_result'), table_name='verification_events')
    op.drop_index(op.f('ix_verification_events_credential_id'), table_name='verification_events')
    op.drop_index('ix_verification_events_credential_company', table_name='verification_events')
    op.drop_index(op.f('ix_verification_events_company_id'), table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index(op.f('ix_share_grant_credentials_credential_id'), table_name='share_grant_credentials')
    op.drop_table('share_grant_credentials')
    op.drop_index(op.f('ix_credential_documents_credential_id'), table_name='credential_documents')
    op.drop_index(op.f('ix_credential_documents_content_hash'), table_name='credential_documents')
    op.drop_table('credential_documents')
    op.drop_index(op.f('ix_share_grants_student_id'), table_name='share_grants')
    op.drop_index('ix_share_grants_student_company', table_name='share_grants')
    op.drop_index(op.f('ix_share_grants_share_token_hash'), table_name='share_grants')
    op.drop_index(op.f('ix_share_grants_company_id'), table_name='share_grants')
    op.drop_table('share_grants')
    op.drop_index('ix_credentials_student_status', table_name='credentials')
    op.drop_index(op.f('ix_credentials_student_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_institution_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credential_identifier'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index('ix_credential_requests_student_status', table_name='credential_requests')
    op.drop_index(op.f('ix_credential_requests_student_id'), table_name='credential_requests')
    op.drop_index(op.f('ix_credential_requests_status'), table_name='credential_requests')
    op.drop_index(op.f('ix_credential_requests_company_id'), table_name='credential_requests')
    op.drop_table('credential_requests')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_identifier'), table_name='students')
    op.drop_index(op.f('ix_students_institution_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_institutions_user_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_activity_logs_entity', table_name='activity_logs')
    op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate's drop_table calls above do NOT drop the Postgres native
    # enum types those columns used (a known Alembic/Postgres-enum gap) — left
    # alone, a downgrade followed by a re-upgrade fails with
    # "type ... already exists". Drop them explicitly, after all tables that
    # reference them are gone.
    bind = op.get_bind()
    sa.Enum(name='verification_result_status').drop(bind, checkfirst=True)
    sa.Enum(name='share_permission').drop(bind, checkfirst=True)
    sa.Enum(name='credential_status').drop(bind, checkfirst=True)
    sa.Enum(name='credential_type').drop(bind, checkfirst=True)
    sa.Enum(name='credential_request_status').drop(bind, checkfirst=True)
    sa.Enum(name='user_role').drop(bind, checkfirst=True)
