"""add blockchain anchoring fields to credentials

Revision ID: fc9bbe8065cb
Revises: 662bf9b6fad9
Create Date: 2026-08-22 14:14:33.826913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9bbe8065cb'
down_revision: Union[str, None] = '662bf9b6fad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


blockchain_anchor_status = sa.Enum('pending', 'anchored', 'failed', name='blockchain_anchor_status')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    blockchain_anchor_status.create(op.get_bind(), checkfirst=True)
    op.add_column('credentials', sa.Column('blockchain_tx_hash', sa.String(length=66), nullable=True))
    op.add_column('credentials', sa.Column('blockchain_network', sa.String(length=50), nullable=True))
    op.add_column('credentials', sa.Column('blockchain_contract_address', sa.String(length=42), nullable=True))
    op.add_column('credentials', sa.Column('blockchain_credential_hash', sa.String(length=66), nullable=True))
    op.add_column('credentials', sa.Column('blockchain_anchored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credentials', sa.Column('blockchain_status', blockchain_anchor_status, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'blockchain_status')
    op.drop_column('credentials', 'blockchain_anchored_at')
    op.drop_column('credentials', 'blockchain_credential_hash')
    op.drop_column('credentials', 'blockchain_contract_address')
    op.drop_column('credentials', 'blockchain_network')
    op.drop_column('credentials', 'blockchain_tx_hash')
    blockchain_anchor_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
